core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login')
]

dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path
from . import views


app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.edit, name='edit'),
    path('new/', views.new, name='new'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)


    class Meta:
        ordering = ['name', ]
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.name
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self) -> str:
        return self.name
    

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Digite seu usuário',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Digite sua senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Digite seu usuário',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Digite seu email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Digite sua senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirme sua senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

item/forms.py
from django import forms
from .models import Item


INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image')

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm



def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    context = {
        'items': items,
        'categories': categories,
    }

    return render(request, 'core/index.html', context)

def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('core:index')

    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {'form': form})

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from item.models import Item
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)

    return render(request, 'dashboard/index.html', {'items': items})

item/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Item
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm



def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    context = {
        'item': item,
        'related_items': related_items,
    }

    return render(request, 'item/detail.html', context)

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {'form': form, 'title': 'Novo item'})

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {'form': form, 'title': 'Editar item'})


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock title %} | Puddle</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Puddle</a>
        <div class="space-x-6">
            <a href="#" class="text-lg font-semibold hover:text-gray-500">New Item</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated %}
            <a href="{% url 'item:new' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Criar Item</a>
            <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Mensagens</a>
            <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Painel de controle</a>
            <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Sair</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Registre-se</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Entrar</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        
        {% endblock content %} 
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            </p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text=lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text=lg text-teal-500 hover:text-teal-700">Contato</a></li>
                <li><a href="#" class="text=lg text-teal-500 hover:text-teal-700">Politica de Privacidade</a></li>
                <li><a href="#" class="text=lg text-teal-500 hover:text-teal-700">Termos de uso</a></li>
            </ul>
        </div>

    </footer>
</body>
</html>

core/templates/core/contact.html
{% extends 'base.html' %}

{% block title %} Contato{% endblock title %}


{% block content %}

    <h1>Página de contato</h1>

{% endblock content %}

core/templates/core/index.html
{% extends 'base.html' %}

{% block title %} Welcome{% endblock title %}


{% block content %}

    <div class="mt-6 px-6 py-12 bg-gray-100 roundes-xl">
        <h2 class="mb-12 text-2xl text-center">
            Novos itens
        </h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" alt="" class="rounded-t-xl">
                        </div>
                        <div class="p-6-white rounded-b-xl">
                            <h2 class="text-2xl"> {{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>

                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 roundes-xl">
        <h2 class="mb-12 text-2xl text-center">
            Categorias
        </h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div class="p-6-white rounded-b-xl">
                    <h2 class="text-2xl"> {{ category.name }}</h2>
                    <p class="text-gray-500">{{ category.items.count }} items</p>
                </div>
            {% endfor %}
        </div>

{% endblock content %}

core/templates/core/login.html
{% extends 'base.html' %}


{% block title %}Entrar{% endblock title %}


{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Entrar</h1>

        <form action="" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="" class="inline-block mb-2">Usuário</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Senha</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                    
                </div>
            {% endif %}

            

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Registrar</button>
        </form>
    </div>

{% endblock content %}

core/templates/core/signup.html
{% extends 'base.html' %}


{% block title %}Registrar-se{% endblock title %}


{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Registrar-se</h1>

        <form action="" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="" class="inline-block mb-2">Usuário</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Senha</label><br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label for="" class="inline-block mb-2">Confirme a senha</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                    
                </div>
            {% endif %}

            

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Registrar</button>
        </form>
    </div>

{% endblock content %}

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}

{% block title %} Welcome{% endblock title %}


{% block content %}

    <div class="mt-6 px-6 py-12 bg-gray-100 roundes-xl">
        <h2 class="mb-12 text-2xl text-center">
            Meus Itens
        </h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" alt="" class="rounded-t-xl">
                        </div>
                        <div class="p-6-white rounded-b-xl">
                            <h2 class="text-2xl"> {{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>

                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

item/templates/item/detail.html
{% extends 'base.html' %}

{% block title %}{{ item.name }}{% endblock title %}

{% block content %}

    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ item.image.url }}" alt="" class="rounded-xl">
        </div>
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl"> {{ item.name }}</h1>
            <p class="text-gray-500"><strong>Price: {{ item.price }}</strong></p>
            <p class="text-gray-500"><strong>Vendedor: {{ item.created_by }}</strong></p>

            {% if item.description %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Descrição: <br></strong>
                    {{ item.description }}
                </p>
            {% endif %}

            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>Esse é seu item</p>
                    <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Editar</a>
                    <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Apagar</a>
                </div>
            {% else %}
                <a href="" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Fale com vendedor</a>
            {% endif %}
            
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 roundes-xl">
        <h2 class="mb-12 text-2xl text-center">
            Itens relacionados
        </h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" alt="" class="rounded-t-xl">
                        </div>
                        <div class="p-6-white rounded-b-xl">
                            <h2 class="text-2xl"> {{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>

                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

item/templates/item/form.html
{% extends 'base.html' %}

{% block title %}{{ title }}  {% endblock title %}  


{% block content %}

    <h1 class="mb-6 text-3xl">
        {{ title }}
    </h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
            
        </div>
    {% endif %}
    <button class="py-4 mt-3 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Salvar item</button>

    </form>

{% endblock content %}